[build]
  command = "npm install && npm run build && cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"
  MONGODB_URI = "mongodb+srv://rainbow11272005_db_user:hhlUjTitzC75B7FQ@cluster1dimpho.jt5rd5s.mongodb.net/?appName=Cluster1Dimpho"
  MONGODB_DB = "dimpho_ke_lesego_catering"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]
  included_files = [
    "dist/**",
    "frontend/dist/**"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
