services:
  - type: web
    name: dimpho-ke-lesego-catering
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: data/dimpho_catering.sqlite
      - key: ADMIN_WHATSAPP_NUMBER
        value: "+27796929591"
      - key: WHATSAPP_NUMBER
        value: "27796929591"
